### ISSUE TITLE
Handle multiple APKs in BITRISE_APK_PATH

### ISSUE THREAD

**Issue by xavier-villelegier** [bitrise-steplib/steps-cordova-archive#24]
Hey !

When the project generates multiple APKs, if I understand correctly, you basically assign BITRISE_APK_PATH to the last file.

The "Deploy play deploy" step can take multiple APKs to deploy, if you provide the paths separated by `|` (ie `whatever/apk1.apk|whatever/apk2.apk`)

Would it be possible to add a boolean input to handle this and make BITRISE_APK_PATH containing all paths separated by `|` ? I think it's just a simple condition here:

 https://github.com/bitrise-community/steps-cordova-archive/blob/5625552ad051b91f58963d3795b047a228cdb0a6/main.go#L145

by concatenating the `outputToExport` with each `destinationPth`.

Thanks for this step by the way ! Cheers ✌️

**Comment by godrei** [comment]
Hi @xavier-villelegier ,
thanks for the issue report. 

Task scheduled to fix this.

Mostly we introduce a separate output for array like outputs, like [BITRISE_APK_PATH_LIST](https://github.com/bitrise-steplib/bitrise-step-android-build/blob/master/step.yml#L86-L93)
