### ISSUE TITLE
Error: Cannot find module 'properties-parser'

### ISSUE THREAD

**Issue by madarco** [bitrise-steplib/steps-cordova-archive#43]
I get this error on bitrise (but this command works correctly locally):

$ cordova "prepare" "android"
Unable to load PlatformApi from platform. Error: Cannot find module 'properties-parser'
Unhandled error. ('The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.')

**Comment by non-binary** [comment]
Hi @madarco,

Can you please enable support access and send over a link to a build?

**Comment by madarco** [comment]
Sure @non-binary, here it is the latest one: https://app.bitrise.io/build/21f9dbfc359422f2#?tab=log

I think problems started when I've updated my cordova ios platform to 6.x

**Comment by non-binary** [comment]
Hi @madarco,

Please see https://stackoverflow.com/a/44336197 and try that and let me know how it goes.
