### ISSUE TITLE
Don't use legacy Xcode build system by default

### ISSUE THREAD

**Issue by ofalvai** [bitrise-steplib/steps-cordova-archive#50]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? latest
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Issue description

The default value of the `options` input is `--buildFlag="-UseModernBuildSystem=0"`. This produces a warning when running with Xcode 12:

```
The legacy build system is deprecated and will be removed in a future release. (62742902)
```

[Xcode 13 beta release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes) mention that this will produce an error now:

```
The legacy build system is deprecated and now produces an error when you attempt to use it. (76124672)
```

### Steps to reproduce

1. Use Xcode 12 or Xcode 13 stack in yuor project
2. Add this step with default options
3. Run

**Comment by manuelabarca** [comment]
I have sent a PR regarding this issue: #53
