### ISSUE TITLE
Invalid OutputDir with Cordova iOS 7.0.0

### ISSUE THREAD

**Issue by DKPillo** [bitrise-steplib/steps-cordova-archive#57]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.0.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [Cordova CLI 12.0.0](https://cordova.apache.org/news/2023/05/22/cordova-cli-12.0.0.html)
- [Cordova iOS 7.0.0](https://cordova.apache.org/announcements/2023/07/10/cordova-ios-7.0.0.html)

### Issue description

In `Cordova iOS 7.0.0` the `CONFIGURATION_BUILD_DIR` overrides have been removed.

This will change the location of where the output files are generated.

- `build/emulator` will become `build/Debug-iphonesimulator`
- `build/device` will become `build/Release-iphoneos`

Therefor the `steps-cordova-archive` breaks for `Cordova iOS 7.0.0` in [main.go:305](https://github.com/bitrise-steplib/steps-cordova-archive/blob/de0126c508b6921564237b3b0083f8647e97fac7/main.go#L305) as the generated path is `platforms/ios/build/device` but should be `platforms/ios/build/Release-iphoneos`. (Same goes for emulator.)

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/dbf915c2-0cbe-411a-80b2-b2be6cd2e0d7)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log (build runs normally, no errors.):

<details>
  <pre>
Collecting android outputs
The apk path is now available in the Environment Variable: BITRISE_APK_PATH (value: /Users/vagrant/deploy/app-release.apk)
Build outputs missing: no ipa generated
  </pre>
</details>

### Steps to reproduce

The Issue can be reproduces by switching to the latest cordova-ios version:

1. `npm remove cordova --force`
2. `npm install -g "cordova@12.0.0" --force`
3. `cordova platform add "ios@7.0.0"`

**Comment by DKPillo** [comment]
In case that anyone else is struggling with this issue and can not wait for a fix of the build step, I would like to share my temporary solution: I have fixed the issue with a workaround by renaming the output directory using an after_compile hook:

```
<platform name="ios">
    <hook type="after_compile" src="scripts/ios/iOSAfterCompile.sh" />
</platform>
```

```
if [ -d "/Users/vagrant/git/platforms/ios/build/Release-iphoneos" ]; then
    mv /Users/vagrant/git/platforms/ios/build/Release-iphoneos /Users/vagrant/git/platforms/ios/build/device
fi
if [ -d "/Users/vagrant/git/platforms/ios/build/Debug-iphonesimulator" ]; then
    mv /Users/vagrant/git/platforms/ios/build/Debug-iphonesimulator /Users/vagrant/git/platforms/ios/build/emulator
fi
```

It is neither pretty nor should it be used as a permanent solution, but for the moment it works.

**Comment by wnabil** [comment]
> In case that anyone else is struggling with this issue and can not wait for a fix of the build step, I would like to share my temporary solution: I have fixed the issue with a workaround by renaming the output directory using an after_compile hook:
> 
> ```
> <platform name="ios">
>     <hook type="after_compile" src="scripts/ios/iOSAfterCompile.sh" />
> </platform>
> ```
> 
> ```
> if [ -d "/Users/vagrant/git/platforms/ios/build/Release-iphoneos" ]; then
>     mv /Users/vagrant/git/platforms/ios/build/Release-iphoneos /Users/vagrant/git/platforms/ios/build/device
> fi
> if [ -d "/Users/vagrant/git/platforms/ios/build/Debug-iphonesimulator" ]; then
>     mv /Users/vagrant/git/platforms/ios/build/Debug-iphonesimulator /Users/vagrant/git/platforms/ios/build/emulator
> fi
> ```
> 
> It is neither pretty nor should it be used as a permanent solution, but for the moment it works.

I knew its something with the build directory location but you saved me a lot of debugging time, Thanks man.
Its also worth mentioning that you need to set the script chmod to +x by adding a script step before running the archive contains 
chmod a+x scripts/ios/iOSAfterCompile.sh

**Comment by ofalvai** [comment]
Hello everyone 👋 

We released a new version of the step with the fix to this problem: https://github.com/bitrise-steplib/steps-cordova-archive/releases/tag/3.0.1
