### ISSUE TITLE
Invalid OutputDir when setting cordova version 12.0.0 or latest or "" /unmodified

### ISSUE THREAD

**Issue by MiguelQueiroz** [bitrise-steplib/steps-cordova-archive#60]
### Troubleshooting

- [ X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.0.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES 

### Issue description

When the steps uses the "latest" cordova version, the output dir of ipa file is not found. This is due to the line of code 176 of the commit https://github.com/bitrise-steplib/steps-cordova-archive/pull/56/commits/dadac2bf4c33bc273ff2560633c0d116d273855e which only read if the cordova version is not empty and greater than 7. 
Because "latest" or "" is a possible value, and not a number it fails the condition, thus falling back to the old way directory. 
Also setting for example "12.0.2" fails because not a number...

Please fix this, thanks.

**Comment by lpusok** [comment]
Hello @MiguelQueiroz,
Release https://github.com/bitrise-steplib/steps-cordova-archive/releases/tag/3.0.3 fixes this,
